config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :bookings
  resources :rooms
  resources :users
  resources :track_bookings

  resources :users do
    member do
      get 'role'
      get 'managerole'
      put 'managerole'
      patch 'managerole'
      post 'manageadmin'
      get 'createnew'
      post 'createnew'
    end
  end

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  layout 'nav'

  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all.where(["b_date > ?", "#{Date.today}"])
    if session[:user_usertype] == 2
      @bookings = Booking.where(["b_date >= ? and user_id = ?", "#{Date.today}", "#{current_user.id}"])
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    if session[:user_usertype] == 2
      @booking.user_id = current_user.id
    end
    #@booking.room_id = @room.id

    if @booking.save
      TrackBooking.create!(:full_name=>@booking.user.full_name, :email=>@booking.user.email, :room_no=>@booking.room.room_no, :size=>@booking.room.size, :lib_name=>@booking.room.lib_name, :b_date=>@booking.b_date, :from_time=>@booking.from_time, :to_time=>@booking.to_time, :status=>'Booked', :booked_by=>session[:user_id], :booking_id=>@booking.id)
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
      if @booking.update(booking_params)
        track = TrackBooking.find_by(booking_id: @booking.id)
        track.update_attributes(:full_name=>@booking.user.full_name, :email=>@booking.user.email, :room_no=>@booking.room.room_no, :size=>@booking.room.size, :lib_name=>@booking.room.lib_name, :b_date=>@booking.b_date, :from_time=>@booking.from_time, :to_time=>@booking.to_time, :status=>'Booking Updated', :booked_by=>session[:user_id], :booking_id=>@booking.id)
        redirect_to @booking, notice: 'Booking was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    track = TrackBooking.find_by(booking_id: @booking.id)
    @booking.destroy
    track.update_attribute(:status, 'Cancelled')
      redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:b_date, :from_time, :to_time, :status, :room_id, :user_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :b_date %>
    <%= f.date_select :b_date, {:default => {:start_year=>Time.now.year}, :end_year=>Time.now.year} %>
  </p>

  <p>
    <%= f.label :from_time %>
    <%= f.time_select :from_time, {:default => (Time.now.beginning_of_hour + 60.minutes)} %>
  </p>

  <p>
    <%= f.label :to_time %>
    <%= f.time_select :to_time, {:default => (Time.now.beginning_of_hour + 120.minutes)} %>
  </p>

    <p>
      <%= f.label :room %><br />
      <%= select("booking", "room_id", Room.all.collect{ |r| [ r.room_no, r.id] }) %>
    </p>

    <% if (session[:user_usertype] == 1 ||session[:user_usertype] == 0) %>
        <p>
          <%= f.label :user %><br />
          <%= select("booking", "user_id", User.all.collect{ |u| [ u.full_name, u.id] }) %>
        </p>
    <% end %>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h2>Current Booking</h2>

<table border='1' cellpadding='6'>

  <tr>
    <th>Name</th>
    <th>Room No.</th>
    <th>Group of</th>
    <th>At</th>
    <th>Booking Date</th>
    <th>From </th>
    <th>To </th>
    <th>Booked On</th>
    <th colspan='2'>Change/Delete</th>
  </tr>

  <% @bookings.each do |track| %>
      <% if (session[:user_usertype]==1 ||session[:user_usertype]==0) %>
          <tr>
            <td><%= track.user.full_name %></td>
            <td><%= track.room.room_no %></td>
            <td><%= track.room.size %></td>
            <td><%= track.room.lib_name %></td>
            <td><%= track.b_date.strftime("%b %d, %Y") %></td>
            <td><%= track.from_time.strftime("%H:%M") %></td>
            <td><%= track.to_time.strftime("%H:%M") %></td>
            <td><%= track.created_at.strftime("%b %d, %Y") %></td>
            <td><%= link_to 'Change Booking', edit_booking_path(track) %></td>
            <td><%= link_to 'Cancel Booking', booking_path(track), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>

      <% else %>
          <% if track.user_id == session[:user_id] %>
              <tr>
                <td><%= track.user.full_name %></td>
                <td><%= track.room.room_no %></td>
                <td><%= track.room.size %></td>
                <td><%= track.room.lib_name %></td>
                <% if !(track.user_id?) %>
                    <td><%= track.b_date %></td>
                    <td><%= track.from_time %></td>
                    <td><%= track.to_time %></td>
                    <td><%= track.created_at %></td>
                <% else %>
                    <td><%= track.b_date.strftime(" %b %d, %Y ") %></td>
                    <td><%= track.from_time.strftime(" %H:%M ") %></td>
                    <td><%= track.to_time.strftime(" %H:%M ") %></td>
                    <td><%= track.created_at.strftime(" %b %d, %Y ") %></td>
              <% end %>
                <td><%= link_to 'Change Booking', edit_booking_path(track) %></td>
                <td><%= link_to 'Cancel Booking', booking_path(track), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>

      <% end %>
  <% end %>
</table>
<br>

app/views/bookings/new.html.erb
<h1>Book a Room now </h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room No:</strong>
  <%= @booking.room.room_no %>
</p>
<p>
  <strong>Booked For Date:</strong>
  <%= @booking.b_date %>
</p>
<p>
  <strong>Booking Done For:</strong>
  <%= @booking.user.full_name %>
</p>
<p>
  <strong>From time:</strong>
  <%= @booking.from_time %>
</p>

<p>
  <strong>To time:</strong>
  <%= @booking.to_time %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>