config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :bookings
  resources :rooms
  resources :users
  resources :track_bookings

  resources :users do
    member do
      get 'role'
      get 'managerole'
      put 'managerole'
      patch 'managerole'
      post 'manageadmin'
      get 'createnew'
      post 'createnew'
    end
  end

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :bookings, dependent: :destroy

  validates :full_name,  presence: true, length: { maximum: 40 }

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false }, presence: true, length: { maximum: 100 }, format: { with: email_regex }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }


  def self.authenticate(email, submitted_password)
    user = find_by_email(email)

    return nil if user.nil?
    return user if user.password == submitted_password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'nav', only: [:edit, :show, :index, :role, :managerole]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end


  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def createnew
    @user = User.new(user_params)

    if @user.save
      ActiveRecord::Base.transaction do
        @user.update_attributes(:usertype=>2, :check=> 0)
      end
      redirect_to users_path
    else
      render 'new'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
        log_in @user
      ActiveRecord::Base.transaction do
        @user.update_attributes(:usertype=>2, :check=> 0)
        session[:user_usertype] = @user.usertype
      end
      flash[:success] = 'Welcome to Library.'
      redirect_to @user
    else
      render 'new'
    end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Changes done successfully..!!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def manageadmin
    @user = User.find(params[:id])
    if @user.usertype == 2
      @user.update_attribute(:usertype, 1)
    elsif @user.usertype == 1
      @user.update_attribute(:usertype, 2)
    end
    redirect_to users_path
  end

  def role
    @user = User.find(params[:id])
  end

  def managerole
    @user = User.find(params[:id])
    if @user.update_attribute(:full_name, params[:user][:full_name])
      flash[:success] = 'Changes have been made successfully..!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :password, :password_confirm, :can_book, :admin, :usertype, :check)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/createnew.html.erb
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>

        <div class="field">
          <%= f.label :full_name %>
          <%= f.text_field :full_name, class: 'form-control' %><br>
        </div>

        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %><br>
        </div>


        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %><br>
        </div>

        <%= f.label :password_confirm, 'Confirmation' %>
        <%= f.password_field :password_confirm, class: 'form-control' %><br>

        <div class="actions">
          <%= f.submit 'Create New Account' %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Personalize</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
        <%= f.label :full_name %>
        <%= f.text_field :full_name, class: 'form-control' %><br>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %><br>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %><br>

        <%= f.label :password_confirm, 'Confirm password' %>
        <%= f.password_field :password_confirm, class: 'form-control'  %><br>

        <%= f.submit 'Save IT', class: 'btn btn-primary'  %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h2>Users list</h2>
<table border ='1' cellpadding="5">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>User Type</th>
    <th colspan='3'>Tasks</th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <% if user.usertype == 0 %>
            <td>Super admin</td>
        <% elsif user.usertype == 1 %>
            <td>Admin</td>
        <% elsif user.usertype == 2 %>
            <td>Library member</td>
        <% end %>
        <td><%= link_to 'Edit', role_user_path(user) %></td>
        <% if user.email != "superadmin@ncsu.edu" and user.email != session[:user_email] %>
            <% if user.check != true %>
                <td><%= link_to 'Delete', user_path(user),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
            <% else %>
                <td> This User has booked the Room.</td>
            <% end %>
            <td><%= link_to 'Assign/Revoke Admin', manageadmin_user_path(user),
                            method: :manageadmin,
                            data: { confirm: 'Are you sure you want to change this user role?' } %></td>
        <% else %>
            <td>Cannot be deleted.</td>
            <td>Already an admin</td>
        <% end %>
      </tr>

  <% end %>
</table>
<%= link_to 'Add New User', new_user_path%>
<br>
User roles:<br>
0 SuperAdmin<br>
1 Admin <br>
2 Library member

app/views/users/new.html.erb
<div><h1>Sign Up</h1></div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>

        <div class="field">
          <%= f.label :full_name %>
          <%= f.text_field :full_name, class: 'form-control' %><br>
        </div>

        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %><br>
        </div>


        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %><br>
        </div>

        <%= f.label :password_confirm, 'Confirmation' %>
        <%= f.password_field :password_confirm, class: 'form-control' %><br>

        <div class="actions">
          <%= f.submit 'Create New Account' %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/role.html.erb
<h1> Profile Update</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :url => {:action => "managerole"} do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, :disabled=>true, class: 'form-control' %><br>

        <%= f.label :full_name %>
        <%= f.text_field :full_name, class: 'form-control'%><br>

        <%= f.submit 'Save Profile', class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h2>
        Welcome, <%= @user.full_name %>
      </h2>
    </section>
  </aside>
</div>
<h3> Perform Task Listed in Tab <br></h3>