config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :bookings
  resources :rooms
  resources :users
  resources :track_bookings

  resources :users do
    member do
      get 'role'
      get 'managerole'
      put 'managerole'
      patch 'managerole'
      post 'manageadmin'
      get 'createnew'
      post 'createnew'
    end
  end

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, :dependent => :destroy

  validates :room_no,  presence: true
  validates :size,  presence: true
  validates :lib_name, presence: true

  def self.search(search)
    if search
      self.where(["room_no = ? or size = ? or lib_name like ? or status like ?", "#{search}".to_i, "#{search}".to_i ,"%#{search}%","%#{search}%"])
    else
      self.all
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  layout 'nav'

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @rooms = @rooms.search(params[:search]) if params[:search].present?
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    @room = Room.new(room_params)
    if @room.save
      redirect_to @room
    else
      render 'new'
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)
      redirect_to @room
    else
      render 'edit'
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    redirect_to rooms_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_no, :size, :lib_name, :status)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :room_no %><br>
      <%= f.number_field :room_no %>
    </p>

    <p>
      <%= f.label :size %><br>
      <%= f.number_field :size , :step => 2, :min => 4, :max => 8 %>
    </p>
    <p>
      <%= f.label :lib_name %><br>
      <%= f.select :lib_name, [['James.B.Hunt','James.B.Hunt'],['D.H.Hill','D.H.Hill']] %>
    </p>
    <p>
      <%= f.label :status %><br>
      <%= f.select :status, [['Available','Available'],['Booked','Booked'],['Rooom Under Construction','Not']] %>
    </p>
    <p>
      <%= f.submit :"Save Room" %>
    </p>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<h2>Room list and Search</h2>
<%= form_tag rooms_path, :method => 'get' do %>
    <p>
      Enter Room No., Size, Library Name or Status<br>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
    </p>
<% end %>
<table border ="1" cellpadding="10">
  <tr>
    <th>Room No. </th>
    <th>Size </th>
    <th>Library Name </th>
    <th colspan="5">Tasks</th>
  </tr>

  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_no %></td>
        <td><%= room.size %></td>
        <td><%= room.lib_name %></td>
        <td><%= link_to 'Show', room_path(room) %></td>
        <% if (session[:user_usertype] == 1 ||session[:user_usertype] == 0) %>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>

            <% if room.status == "Available" || room.status == "Not" %>
                <td><%= link_to 'Delete', room_path(room),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
            <% else %>
                <td> The Room is Booked. </td>
            <% end %>
        <% end %>
        <% if room.status == "Available" || room.status =="Booked" %>
            <td>Booking Available</td>
        <% end %>
        <% if room.status == 'Not'%>
            <td>Not in Use</td>
        <% end %>
      </tr>
  <% end %>
</table>
<% if (session[:user_usertype]==1 ||session[:user_usertype]==0) %>
    <br/></br>
    <%= link_to 'Add New Room', new_room_path, :class=>"buttonDesign" %><br>
    <%= link_to 'Book Room for User', new_booking_path %>
<% else %>
    <br/><br/>
    <%= link_to 'Go For Booking', new_booking_path %>
<% end %>

app/views/rooms/new.html.erb
<h1>Add Room</h1>

<%= form_for @room do |f| %>

    <p>
      <%= f.label :room_no %>
      <%= f.number_field :room_no , :min=>0, :max=>9999 %>
    </p>

    <p>
      <%= f.label :size %>
      <%= f.select :size, [[4,4],[6,6],[8,8]] %>
    </p>


    <p>
      <%= f.label :lib_name %>
      <%= f.select :lib_name, [['James.B.Hunt','James.B.Hunt'],['D.H.Hill','D.H.Hill']] %>
    </p>


    <p>
      <%= f.label :status %><br>
      <%= f.select :status, [['Available','Available'],['Rooom Under Construction','Not']] %>
    </p>

    <p>
      <%= f.submit 'Add New Room' %>
    </p>

<% end %>

app/views/rooms/search.html.erb
<h4>Rooms Searching Engine</h4>
<%= form_for @room do |f| %>
    <p>
      <%= f.label :room_no %><br>
      <%= f.number_field :room_no %>
    </p>

    <p>
      <%= f.label :size %><br>
      <%= f.number_field :size %>
    </p>
    <p>
      <%= f.label :lib_name %><br>
      <%= f.text_field :lib_name %>
    </p>
    <p>
      <%= f.label :Status %><br>
      <%= f.select :status, [['Available','Available'],['Booked','Booked']] %>
    </p>
    <p>
      <%= f.submit :"Search" %>
    </p>
<% end %>

app/views/rooms/show.html.erb
<h2>Room details</h2>
<div>
  <p>
    <strong>Room No: </strong>
    <%= @room.room_no %>
  </p>

  <p>
    <strong>Size: </strong>
    <%= @room.size %>
  </p>

  <p>
    <strong>Library: </strong>
    <%= @room.lib_name %>
  </p>

  <p>
    <strong>Status: </strong>
    <%= @room.status %>
  </p>

</div>

<%= link_to 'Room List', rooms_path %>
<% if (session[:user_usertype]==2) %>
    <br/>
    <%= link_to 'Check for Booking Availablility', new_booking_path %>
<% end %>