config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :bookings
  resources :rooms
  resources :users
  resources :track_bookings

  resources :users do
    member do
      get 'role'
      get 'managerole'
      put 'managerole'
      patch 'managerole'
      post 'manageadmin'
      get 'createnew'
      post 'createnew'
    end
  end

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library Room Management System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <h1>Library Management System</h1>
  <i><h5 align="right" >Seeking a secure place to study? Lets reserve a Room ... </h5></i>
</div>
  </div>
<header class="">
  <div class="container">
    <div id="nav1">
      <ul class="">
        <% if logged_in? %>
            <p>
              You are already logged in. <%= link_to 'Go To Home Page.', current_user %>
            </p>
        <% else %>
           <div id="nav1">Already a user?<%= link_to 'Log in', login_path %></div>
        <% end %>
      </ul>
    </div>
  </div>
</header>
<div class="nav1">
  <% flash.each do |message_type, message| %>
      <b><div class="alert alert-<%= message_type %>"><%= message %></div></b>
  <% end %>
  <div id="main">

    <%= yield %>
  </div>
</div>
<div id="footer">
  Developed and Maintained by Animesh, Prerit & Gautami
</div>
</body>
</html>

app/views/layouts/nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lib</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <h1>Library Management System</h1>
  <i><h5 align="right" >Seeking a secure place to study? Lets reserve a Room ... </h5></i>
</div>

<div id="nav">
  <% if (session[:user_usertype]==1 ||session[:user_usertype]==0) %>
      <%= link_to 'Manage Users / Admins', controller: 'users' %> <br>
      <%= link_to 'Manage Rooms', controller: 'rooms' %>&emsp;&emsp;&emsp;&emsp;&emsp;
      <%= link_to 'Reserve Room for User', new_booking_path %><br>
  <% else %>
      <%= link_to 'Look for Room', controller: 'rooms' %>&emsp;&emsp;&emsp;&emsp;&emsp;
      <%= link_to 'Directly Go for Booking', new_booking_path %><br>
  <% end %>
  <% if (session[:user_usertype]==1 ||session[:user_usertype]==0) %>
      <%= link_to 'Current Bookings', controller: 'bookings' %>&emsp;&emsp;&emsp;&emsp;
      <%= link_to 'Past Bookings', controller: 'track_bookings' %><br>
<% else %>
      <%= link_to 'Current Booking', controller: 'bookings' %>&emsp;&emsp;&emsp;&emsp;
      <%= link_to 'Past Bookings', controller: 'track_bookings' %><br>
  <% end %>
  <%= link_to "Update Profile", edit_user_path(current_user) %><br>


  <%= link_to "Logout", logout_path, method: "delete" %><br>

  <%= yield %>

  <div id="footer">
    Developed and Maintained by Animesh, Prerit & Gautami
  </div>
</div>
</body>
</html>